# Generated by Django 5.2.6 on 2025-09-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
