# Generated by Django 5.2.6 on 2025-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('jersey', 'Jersey'), ('celana', 'Celana')], default='sepatu', max_length=20),
        ),
    ]
