# Generated by Django 5.2.6 on 2025-09-15 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ccreated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
