# Generated by Django 5.2.6 on 2025-09-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_ccreated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ccreated_at',
            new_name='created_at',
        ),
    ]
